complete -c toggl -a current
complete -c toggl -a stop
complete -c toggl -a ts
complete -c toggl -a ws
complete -c toggl -a lunch
complete -c toggl -a break
complete -c toggl -a start
complete -c toggl -a projects
complete -c toggl -a newproj
complete -c toggl -a update_proj
