#!/bin/env bash

# Home directory for Windows.
export H=/mnt/c/Users/mpaulus

export PATH=~/dotfiles/scripts:/usr/local/texlive/2018/:"$PATH"

setterm -cursor on
PROMPT_DIRTRIM=5

# Make tmux start in Windows home directory
if [ -z "$TMUX" ]; then
    cd /mnt/c/Users/mpaulus || return
fi

[ -f ~/.fzf.bash ] && source ~/.fzf.bash

export NNN_TMPFILE="/tmp/nnn"

n()
{
    nnn "$@"

    if [ -f $NNN_TMPFILE ]; then
        . $NNN_TMPFILE
        rm -f $NNN_TMPFILE > /dev/null
    fi
}

i() { nvim ./*.idf ; }

export FFF_CD_FILE=~/.fff_d
f() { fff "$@"; cd "$(cat ~/.fff_d)" || exit; }


et() {
    nvim "/mnt/c/Users/mpaulus/OneDrive - Command Commissioning/dailynotes/tasks.markdown"
}

ashrae() {
    pushd '/mnt/c/Users/mpaulus/Command Commissioning/Library - Guidelines and Standards/ASHRAE' >/dev/null
    cmd.exe /C start '' "$(fd -e pdf | fzf)"
    popd >/dev/null
}

# Explorer.exe here
eh() { explorer.exe "$(wslpath -w "$(pwd)")"; }

epidd() { nvim '/mnt/c/EnergyPlusV9-2-0/Energy+.idd'; }

export NEOVIM_WIN_DIR="/mnt/c/Users/mpaulus/scoop/apps/neovim/current/Neovim"

alias ep='/mnt/c/EnergyPlusV9-2-0/energyplus.exe'

# Resource Advisor API location
export raapi="https://preprod.resourceadvisor.schneider-electric.com/api"
export iancred="inelson:CCllc2019!"

export ratest="https://core.stg1.resourceadvisor.schneider-electric.com/api"

brand_colors_png() {
    cmd.exe '/C' 'C:\Users\mpaulus\OneDrive - Command Commissioning\ccllc_brand_colors.png'
}

brand_colors() {
    printf "Blue:       0   73  135, #004987\n"
    printf "Gray:       84  88  90,  #54585a\n"
    printf "Maroon:     80  0   0,   #500000\n"
    printf "Light Gray: 237 240 240, #edf0f0\n"
    printf "Green:      25  145 58,  #19913a\n"
    printf "Yellow:     253 196 0,   #fdc400\n"
    printf "Black:      0   0   0,   #000000\n"
}

# vim:ft=sh
