#!/bin/env bash
pathadd /usr/local/texlive/2020/bin/x86_64-linux
export MANPATH=/usr/local/texlive/2020/texmf-dist/doc/man/:$MANPATH
export INFOPATH=/usr/local/texlive/2020/texmf-dist/doc/info/:$INFOPATH

export GEM_HOME=$HOME/gems
pathadd "$HOME/gems/bin"
pathadd "$HOME/bin"
pathadd "$HOME/.gem/ruby/2.7.0/bin"

PS1='\[\e[90m\]\w $(gitbranch) $(gitmod) \n\[\e[90m\]::\[\e[00m\] '

# Goto plugins
gp() {
    cd ~/.vim/pack/mitchplugins/start/ || return
}

# Function to display the current git branch
gitbranch() {
    git branch 2> /dev/null | awk '/\*/ { printf("\033[31m<%s>\033[0m", $2) }'
}

gitmod() {
    if [[ "$(gitbranch)" ]]; then
        printf "\033[31m%s↑ \033[32m%s+\033[0m" "$(git status -su | awk '/^\sM\s/' | wc -l)" \
            "$(git status -su | awk '/^\s*\?\?\s+/' | wc -l)"
    fi
}

alias vim=nvim
# vim:ft=sh
