map global insert <c-w> -docstring 'delete previous word' %{<esc>bdi}

# exit insert mode with jk
# See: https://www.reddit.com/r/kakoune/comments/grlu0s/comment/frzp6g9/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button
hook global InsertChar f %{ try %{
  exec -draft hH <a-k>jf<ret> d
  exec <esc>
}}

map global normal <c-l> <a-l>
map global normal <c-h> <a-h>

