map global insert <c-w> -docstring 'delete previous word' %{<esc>bdi}

# exit insert mode with jk.
# See: https://www.reddit.com/r/kakoune/comments/grlu0s/comment/frzp6g9/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button
hook global InsertChar f %{ try %{
  exec -draft hH <a-k>jf<ret> d
  exec <esc>
}}

map global normal L gl
map global normal H gh
map -docstring 'Next buffer' global normal <c-n> :bn<ret>
# Can't really live without these two mappings.
map global normal q :q<ret>
map global normal Q :q!<ret>
map global normal s :w<ret>
# Old habits die hard
map global normal z vc
map global user z z

map global normal <c-u> 5k
map global normal <c-d> 5j

map global normal C Glc
map global normal <a-c> C

# Recreation of Vim D for now. Didn't look like it's bound to anything by default in Kakoune
map global normal D Gld
map -docstring 'Run macro (q)' global user q q
map -docstring 'Start or end macro' global user Q Q
map -docstring 'Search selection' global user s s
map -docstring 'Inner select' global user i <a-i>
map -docstring 'Outer select' global user a <a-a>
map global user y <a-|>clip<ret>

add-highlighter global/ number-lines -relative -separator ' '

set-option global tabstop 4
set-option global indentwidth 4
set-option global scrolloff 10,0
set-option global ui_options terminal_enable_mouse=true

colorscheme desertex

# This is stolen from https://github.com/hadronized/config/blob/master/kak/kakrc
declare-user-mode match
map global match a '<a-a>' -docstring 'match around'
map global match i '<a-i>' -docstring 'match inside'
map global match m m -docstring 'select other matching delimiter'

map global normal m ':enter-user-mode match<ret>' -docstring 'Enter match mode'

# I prefer to generally swap the ALT mappings with the SHIFT versions.
# Basically, I don't find myself 'extending' selections all that often.
map global normal <a-e> E
map global normal <a-b> B
map global normal E <a-e>
map global normal B <a-b>
