#!/bin/sh

# Install script for remind

curl -o /tmp/remind-04.00.03.tar.gz 'https://dianne.skoll.ca/projects/remind/download/remind-04.00.03.tar.gz'

# Instructions straight from the remind website
cd /tmp && tar xfz /tmp/remind-04.00.03.tar.gz && cd /tmp/remind-04.00.03 && ./configure && make && make test && sudo make install
