#!/bin/sh
set -e

if test -z "$LOCALBIN"; then
    printf "Variable LOCALBIN must be set.\n"
    exit 1
fi

latest_asset="$(curl -s https://api.github.com/repos/BurntSushi/ripgrep/releases/latest)"
asset="$(printf "%s" "$latest_asset" | jq -r '.assets[] | select(.name | contains("amd64")) | .browser_download_url')"
name="$(printf "%s" "$latest_asset" | jq -r '.assets[] | select(.name | contains("amd64")) | .name')"
# Need to follow redirects with '-L' to get the actual file.
curl --output /tmp/"$name" -L "$asset"
sudo dpkg -i /tmp/"$name"
