#!/bin/sh
set -e

# $1 - github URL
# $2 - Regex to match asset

latest_release="$(latest_release "$1")"
download="$(printf "%s" "$latest_release" | github_releases.py "$2")"
asset="$(printf "%s" "$download" | awk 'NR == 1')"
name="$(printf "%s" "$download" | awk 'NR == 2')"
# Need to follow redirects with '-L' to get the actual file.
curl --output /tmp/"$name" -L "$asset"
sudo dpkg -i /tmp/"$name"
