#!/bin/sh

latest_release="$(latest_release be5invis Iosevka)"
download="$(printf "%s" "$latest_release" | github_releases.py '^ttf-iosevka-term-[0-9]+\.[0-9]+\.[0-9]+\.zip$')"
asset="$(printf "%s" "$download" | awk 'NR == 1')"
name="$(printf "%s" "$download" | awk 'NR == 2')"

# Need to follow redirects with '-L' to get the actual file.
FOLDER=/tmp/"$(basename "$name" .zip)"
mkdir -p "$FOLDER"
curl --output /tmp/"$name" -L "$asset"

# Unzip in tmp directory
unzip /tmp/"$name" -d "$FOLDER"

printf "Move font file from '%s' to proper location\n" "$FOLDER" >&2
