#!/bin/sh
set -e

if test -z "$LOCALBIN"; then
    printf "Variable LOCALBIN must be set.\n"
    exit 1
fi

latest_release="$(latest_release EricChiang pup)"
download="$(printf "%s" "$latest_release" | github_releases.py 'pup_v[0-9]\.[0-9]\.[0-9]_linux_amd64.zip')"
asset="$(printf "%s" "$download" | awk 'NR == 1')"
name="$(printf "%s" "$download" | awk 'NR == 2')"
# Need to follow redirects with '-L' to get the actual file.
curl --output /tmp/"$name" -L "$asset"

unzip /tmp/"$name" -d "$LOCALBIN"

