#!/bin/sh
set -e

latest_asset="$(curl -s https://api.github.com/repos/sharkdp/fd/releases/latest)"
asset="$(printf "%s" "$latest_asset" | jq -r '.assets[] | .browser_download_url' | awk '/fd_[0-9]+\.[0-9]+\.[0-9]+_amd64.deb/' )"
name="$(printf "%s" "$latest_asset" | jq -r '.assets[] |  .name'  | awk '/fd_[0-9]+\.[0-9]+\.[0-9]+_amd64.deb/' )"
# Need to follow redirects with '-L' to get the actual file.
curl --output /tmp/"$name" -L "$asset"
sudo dpkg -i /tmp/"$name"
