#!/bin/sh
set -e

latest_release="$(latest_release fish-shell fish-shell)"
download="$(printf "%s" "$latest_release" | github_releases.py 'fish-[0-9]\.[0-9]\.[0-9].tar.xz')"
asset="$(printf "%s" "$download" | awk 'NR == 1')"
name="$(printf "%s" "$download" | awk 'NR == 2')"
# Need to follow redirects with '-L' to get the actual file.
curl --output /tmp/fish -L "$asset"
tar -C /tmp/ -x -f /tmp/"$name"

cd /tmp/fish-*/
cmake . && make && sudo make install
