#!/bin/sh

set -e

# TMSU (Tag my shit up)

download="$(latest_release oniony TMSU | github_releases.py '.tgz$')"
asset="$(printf "%s" "$download" | awk 'NR == 1')"
name="$(printf "%s" "$download" | awk 'NR == 2')"
# Need to follow redirects with '-L' to get the actual file.
printf "Downloading to %s\n" /tmp/"$name"
curl --output /tmp/"$name" -L "$asset"

expected_extracted_dir=/tmp/"$(basename "$name" .tgz)"
rm -rf "$expected_extracted_dir"
tar -C /tmp -x -f /tmp/"$name"
sudo mkdir -p /usr/local/tmsu
sudo rm -rf /usr/local/tmsu/*
sudo mv "$expected_extracted_dir"/* /usr/local/tmsu

for file in /usr/local/tmsu/bin/*; do
    sudo ln -s -f -t /usr/local/bin "$file"
done

sudo mkdir -p /usr/local/share/man/man1
sudo ln -s -f /usr/local/tmsu/man/tmsu.1.gz /usr/local/share/man/man1/tmsu.1.gz
