#!/usr/bin/env python3
import sys
from pathlib import Path

filepath = Path(sys.argv[1])
filename = filepath.name

def to_csv_cell(text):
    must_quote = "," in text or '"' in text or '\r' in text or '\n' in text
    if not must_quote:
        return text

    chars = ['"']
    for char in text:
        if char == '"':
            chars.append('"')
        chars.append(char)
    chars.append('"')
    return ''.join(chars)

# Strip '.csv' or '.tsv' from filename
if filename.endswith('.csv'):
    delim = ','
    filename = to_csv_cell(filename[:-4])
elif filename.endswith('.tsv'):
    delim = '\t'
    filename = filename[:-4]
else:
    print("File does not end with '.csv' or '.tsv'")
    sys.exit()

print(f"Timestamp{delim}{filename}\n", end='')
for line in filepath.open():
    try:
        print(line.rstrip(), end='\n')
    except BrokenPipeError:
        break
