#!/bin/sh
set -e

cd "$DOTFILES"  || exit 1

# Set LC_ALL to C to avoid problems with locales.
export LC_ALL=C

# Sort the 'vim/spell/hvac.utf-8.add' file in place.
# Sorting helps to avoid merge conflicts that happen if everything
# is just appended at the end.
sort vim/spell/hvac.utf-8.add > vim/spell/hvac.utf-8.add.tmp
mv vim/spell/hvac.utf-8.add.tmp vim/spell/hvac.utf-8.add

git add 'vim/spell/hvac.utf-8.add' && \
git commit -m 'Add spellings' && \
git push
