#!/usr/bin/awk -E

BEGIN {
    type = "AVERAGE"

    arg1 = ""
    arg2 = ""
    arg3 = ""

    for (i = 1; i < ARGC; i++) {
        if (ARGV[i] == "-h" || ARGV[i] == "--help") {
            print "Usage: binexcel [-c] <Avg or Count col> <Creiteria Col> <Bin > Cell>" ;
            print "Ex: binexcel A B C10" ;
            exit 0;
        }
        else if (ARGV[i] == "-c" || ARGV[i] == "--count") {
            type = "COUNT"
            ARGV[i] = ""
        }
        else {
            arg1 = ARGV[i]
            ARGV[i] = ""
            arg2 = ARGV[i + 1]
            ARGV[i + 1] = ""
            arg3 = ARGV[i + 2]
            ARGV[i + 2] = ""
            i += 2
        }
    }

    if (arg1 == "" || arg2 == "" || arg3 == "") {
        print "Missing positional arguments (Need 3)"
        print "Usage: binexcel [-c] <Avg or Count col> <Creiteria Col> <Bin > Cell>" ;
        print "Ex: binexcel A B C10" ;
        exit 0;
    }

    # {{{ Letters
    next_letter["A"] = "B";
    next_letter["B"] = "C";
    next_letter["C"] = "D";
    next_letter["D"] = "E";
    next_letter["E"] = "F";
    next_letter["F"] = "G";
    next_letter["G"] = "H";
    next_letter["H"] = "I";
    next_letter["I"] = "J";
    next_letter["J"] = "K";
    next_letter["K"] = "L";
    next_letter["L"] = "M";
    next_letter["M"] = "N";
    next_letter["N"] = "O";
    next_letter["O"] = "P";
    next_letter["P"] = "Q";
    next_letter["Q"] = "R";
    next_letter["R"] = "S";
    next_letter["S"] = "T";
    next_letter["T"] = "U";
    next_letter["U"] = "V";
    next_letter["V"] = "W";
    next_letter["W"] = "X";
    next_letter["X"] = "Y";
    next_letter["Y"] = "Z";
    next_letter["Z"] = "AA";
    next_letter["AA"] = "AB";
    # }}}

    average_col           = arg1
    criteria_col          = arg2
    bin_greater_than_cell = arg3

    ARGV[1] = "";
    ARGV[2] = "";
    ARGV[3] = "";

    if (type == "COUNT") {
        excel_function = "COUNTIF"
    }
    else {
        excel_function = "AVERAGEIFS"
    }

    match(bin_greater_than_cell, /^[A-Z]+/)
    bin_letter = substr(bin_greater_than_cell, 1, RLENGTH);
    bin_row    = substr(bin_greater_than_cell, RLENGTH + 1);

    printf "=%s(%s:%s,%s:%s,\">\"&%s,%s:%s,\"<=\"&%s)\n", excel_function, average_col, average_col, criteria_col, criteria_col, bin_greater_than_cell, criteria_col, criteria_col, (next_letter[bin_letter] bin_row) ;
}
