#!/bin/sh
printf "Blue:       0   73  135  #004987\n"
printf "Gray:       84  88  90   #54585a\n"
printf "Maroon:     80  0   0    #500000\n"
printf "Light Gray: 237 240 240  #edf0f0\n"
printf "Green:      25  145 58   #19913a\n"
printf "Yellow:     253 196 0    #fdc400\n"
printf "Black:      0   0   0    #000000\n"
