#!/usr/bin/env python3

# Inspired by: https://unix.stackexchange.com/a/359838/296724
# Why use python? Because I don't have time to deal with RFC 4180 subtlities
# right now.
#
# Use with standard input or pass single file name (expected file is utf-8).
#
# csv2tsv < file.csv
# program | csv2tsv
# csv2tsv file.csv

import csv
import sys


help_text = (
"""csv2tsv

USAGE: csv2tsv file

This will take a CSV file, possibly formatted under RFC 4180, and turn it into
a tab separated file.
"""
)

if (any([ arg == "-h" or arg == "--help" for arg in sys.argv])):
    print(help_text, end='')
    sys.exit()

if (len(sys.argv) > 1):
    csv_file = open(sys.argv[1], encoding="utf-8")
else:
    csv_file = sys.stdin

reader = csv.reader(csv_file, dialect='excel')

for row in reader:
    # The only two characters that matter here are newlines and tabs. Remove both.
    new_rows = [field.replace("\n", "\\n").replace("\t", "\\t") for field in row]
    print("\t".join(new_rows))
