#!/usr/bin/awk -E

# Purpose of this script is to
BEGIN {

    if (ARGV[1] == "-h" || ARGV[1] == "--help") {
        print "cubic_excel"
        print ""
        print "USAGE:"
        print "cubic_excel START_COL START_ROW X_INPUT [SHEET]"
        print ""
        print "Expects that the coefficients are vertical, beginning at START_COL and START_ROW"
        exit 0
    }

    start_col = ARGV[1]
    start_row = ARGV[2]
    x_cell = ARGV[3]

    sheet = ARGV[4]

    if (sheet != "") {
        total_sheet = "'" sheet "'!"
    }
    else {
        total_sheet = ""
    }

    constant = total_sheet "$" start_col "$" start_row
    x        = total_sheet "$" start_col "$" (start_row + 1)
    xx       = total_sheet "$" start_col "$" (start_row + 2)
    xxx       = total_sheet "$" start_col "$" (start_row + 3)

    printf "=%s + (%s * %s) + (%s * %s * %s) + (%s * %s * %s * %s)", constant, x, x_cell, xx, x_cell, x_cell, xxx, x_cell, x_cell, x_cell
}
