#!/usr/bin/awk -E

# See Tomohiko Sakamoto algorithm
BEGIN {

    # Check for help
    for (i = 1; i < ARGC; i++) {
        if (ARGV[i] == "-h" || ARGV[i] == "--help") {
            print "dow - determine day of the week\n\ndow year month day\n\nyear  = 4 digit year\nmonth = 1-12\nday   = 1-31"
            exit 0
        }
    }

    if (ARGC != 4) {
        print "dow expects 3 arguments, received " (ARGC - 1)
        exit 1
    }

    year = ARGV[1]
    month = ARGV[2]
    day = ARGV[3]

    offset[0] = 0
    offset[1] = 3
    offset[2] = 2
    offset[3] = 5
    offset[4] = 0
    offset[5] = 3
    offset[6] = 5
    offset[7] = 1
    offset[8] = 4
    offset[9] = 6
    offset[10] = 2
    offset[11] = 4

    ARGV[1] = ""
    ARGV[2] = ""
    ARGV[3] = ""

    dow[0] = "Sunday"
    dow[1] = "Monday"
    dow[2] = "Tuesday"
    dow[3] = "Wednesday"
    dow[4] = "Thursday"
    dow[5] = "Friday"
    dow[6] = "Saturday"

    if (month < 3) year -= 1
    dow_num = (year + int(year / 4) - int(year / 100)  + int(year / 400) + offset[month - 1] + day) % 7
    print  dow_num, dow[dow_num]
}
