#!/usr/bin/awk -E
#
# This script for detecting duplicates also prints the lines that they occur in.
BEGIN {
    OFS="\t"

    # @h
    help = 0
    idx = 0
    while (idx < ARGC) {
        if (ARGV[idx] == "-h" || ARGV[idx] == "--help")
        {
            help = 1
            ARGV[idx] = ""
            idx++;
        }
        idx++
    }

    if (help == 1)
    {
        print "Usage: " FILENAME " [options] [file]"
        print "Options:"
        print "  -h, --help  Print this help message"
        exit 0
    }

}

{
    if ($0 in lines) {
        lines[$0] = lines[$0] " " NR
        dups[$0]
    }
    else {
        lines[$0] = NR
    }
}

END {
    for (dup in dups) {
        print lines[dup], dup
    }
}
