#!/usr/bin/env python3

import chardet
import sys

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: {} <file>".format(sys.argv[0]))
        sys.exit(1)

    with open(sys.argv[1], "rb") as f:
        data = f.read()
        result = chardet.detect(data)
        print(f'{sys.argv[1]}: {result["encoding"]}')
