#!/usr/bin/python3
import sys
import mputils

# Read first two arguments as files
args = sys.argv[1:]

if len(args) != 2:
    print("Usage: ep_annual_savings.py <baseline> <proposed>")
    sys.exit(1)

try:
    baseline = mputils.annual_facility_electricity(args[0])
except:
    print("Error reading baseline file")
    sys.exit(1)

try:
    proposed = mputils.annual_facility_electricity(args[1])
except:
    print("Error reading proposed file")
    sys.exit(1)

print("Baseline: %s kWh" % baseline)
print("Proposed: %s kWh" % proposed)
print("Savings: %s kWh" % (baseline - proposed))
