#!/usr/bin/env python3

# Print all extensions from lines in stdin

import sys

exts = set()

for line in sys.stdin:

    file_split = line.split('/')

    filename = file_split[-1]

    split = filename.split('.')

    if len(split) == 2 and filename[0] == ".":
        # Dotfile, return entire line
        exts.add(filename.strip())

    if len(split) > 1:
        exts.add("." + split[-1].rstrip())

    if len(split) == 1:
        exts.add(filename.strip())

exts = sorted(exts)
for ext in exts:
    print(ext)
