#!/usr/bin/awk -E

BEGIN {

    help_text = "f2c - Convert Fahrenheit to Celcius\n\nUSAGE:\n\n    f2c FahrenheitTemp"

    # First argument is command name
    if (ARGC < 2) { print "No temperature entered.\n\n" help_text ; exit }

    for (i in ARGV) {
        if (ARGV[i] == "-h" || ARGV[i] == "--help") {
            print help_text
            exit 0
        }
    }

    print (ARGV[1] - 32) * 5 / 9

    # Make sure this isn't read as a filename
    ARGV[1] = ""
}

# vim:ft=awk
