#!/bin/sh

# This script changes all spaces in filenames to underscores
for file in *; do
    case "$file" in
        *' '* )
            mv "$file" "$(printf "%s" "$file" | sed 's/ /_/g' )"
        ;;
    esac
done
