#!/bin/sh

# Verify that java is installed and available
if command -v java >/dev/null 2>&1; then
    # Check for file ~/.local/genopt/genopt.jar
    if [ -f ~/.local/genopt/genopt.jar ]; then
        # Run GenOpt
        java -jar ~/.local/genopt/genopt.jar "$@"
    elif [ -f ~/apps/genopt/genopt.jar ]; then
        # Run GenOpt
        java -jar ~/apps/genopt/genopt.jar "$@"
    else
        echo "GenOpt is not installed at ~/.local/genopt/genopt.jar or ~/apps/genopt/genopt.jar."
        exit 1
    fi
else
    echo "Java is not installed to run GenOpt."
    exit 1
fi
