#!/bin/sh

latest_asset="$(curl -s https://api.github.com/repos/"$1"/releases/latest)"
asset="$(printf "%s" "$latest_asset" | jq -r ".assets[] | select(.name | contains(\"$2\")) | .browser_download_url")"
name="$(printf "%s" "$latest_asset" | jq -r ".assets[] | select(.name | contains(\"$2\")) | .name")"
# Need to follow redirects with '-L' to get the actual file.

curl -s --output /tmp/"$name" -L "$asset"
printf "%s\n" "$name"
