#!/bin/sh

# Check that first argument is an integer, greater than 0
if [ $# -ne 1 ] || [ "$1" -lt 1 ] 2>/dev/null; then
    echo "Usage: $0 <field number>"
    exit 1
fi

awk -F '	' '{print $'"$1"'}' | mpuniq -c | sort -V
