#!/usr/bin/awk -E

# Takes tab-separated column headers from copying out of Excel,
# and turns them into variable names and assignments.

BEGIN {
    FS=OFS="\t"
    python_form = 0

    for (i = 1; i <= ARGC; i++) {
        if (ARGV[i] == "-p") {
            python_form = 1
            ARGV[i] = ""
        }
    }
}

NR == 1 {
    for (i = 1; i <= NF; i++) {

        header = $i

        gsub(/#/, "num", header)
        gsub(/²/, "2", header)
        gsub(/³/ "3", header)
        gsub(/°/, "deg", header)
        gsub(/[^a-zA-Z0-9]/, "_", header)
        gsub(/__+/, "_", header)
        gsub(/#/, "num", header) # Things like 'Package #', 'Issue #', etc.

        gsub(/_$/, "", header)

        header = tolower(header)

        if (python_form) {
            printf "%s = %d\n", header, i
        }
        else {
            printf "%s = $%s\n", header, i
        }

    }
}
