#!/usr/bin/awk -E

# Takes tab-separated column headers from copying out of Excel,
# and turns them into variable names and assignments.

BEGIN { FS=OFS="\t" }

NR == 1 {
    for (i = 1; i <= NF; i++) {

        header = $i

        gsub(/#/, "num", header)
        gsub(/²/, "2", header)
        gsub(/³/ "3", header)
        gsub(/°/, "deg", header)
        gsub(/[^a-zA-Z0-9]/, "_", header)
        gsub(/__+/, "_", header)
        gsub(/#/, "num", header) # Things like 'Package #', 'Issue #', etc.

        gsub(/_$/, "", header)

        header = tolower(header)

        printf "%s = $%s\n", header, i
    }
}
