#!/bin/sh

set -e

# Normally it's expected that the repo:
# https://github.com/mitchpaulus/idf-default-objects
# has been cloned to a directory within `HOME` somewhere.

# Allow myself to set the directory arbitrarily in a particular dir. Also serves
# as cached location, so the directory doesn't have to be searched for each time.
if test -f "$HOME"/.config/idf-default-objects/dir; then
    DIR="$(cat "$HOME"/.config/idf-default-objects/dir)"
else
    # Search for directory named 'idf-default-objects'
    REPODIR="$(fd --type d idf-default-objects "$HOME")"
    if test -n "$REPODIR"; then
        # Get the latest version available
        DIR="$(fd --type d '^[0-9]' "$REPODIR" | sort -V -r | head -n 1)"
        mkdir -p "$HOME"/.config/idf-default-objects
        # Write the file location to a cached location
        printf "%s\n" "$DIR" > "$HOME"/.config/idf-default-objects/dir
    else
        printf "Could not find repository directory.\n"
        exit 1
    fi
fi

if test ! -d "$DIR"; then
    printf 'The cached directory "%s" at "%s" does not exist.' "$DIR" "$HOME"/.config/idf-default-objects/dir
    exit 1
fi

filepath="$DIR"/"$(fd '.' "$DIR" -x basename | fzf)"

# Send filenames into fzf, then use appropriate clipboard functionality
if test -n "$WSL_DISTRO_NAME"; then
    clip.exe < "$filepath"
else
    xclip -selection clipboard < "$filepath"
fi
