#!/usr/bin/env python3

# Going from Influx 'Annotated CSV' to an MP file
import csv
import sys
import re

import zoneinfo
import tzdata
import datetime

from typing import List, Union, Iterable, Optional

def convert_to_int_if_possible(s: str) -> Union[int, str]:
    """
    Convert the given string to an int if possible. Otherwise, return the
    original string.
    """
    return int(s) if s.isdigit() else s

def alphanum_key(s) -> List[Union[str, int]]:
    """ Turn a string into a list of string and number chunks.
        "z23a" -> ["z", 23, "a"]
    """
    #  return [convert_to_int_if_possible(c) for c in re.split('([0-9]+)', s) if convert_to_int_if_possible(c) != ""]
    return [convert_to_int_if_possible(c) for c in re.split('([0-9]+)', s.lower())]

# Basically taken from https://stackoverflow.com/a/2669120/5932184
def version_sort(l: Iterable[str]) -> List[str]:
    """ Sort the given iterable in the way that humans expect."""
    return sorted(l, key=alphanum_key)


def parse(col_name: Optional[str]) -> dict:
    csv_reader = csv.reader(sys.stdin)
    data = {}

    measurement_name = col_name if col_name else "_measurement"

    time_col = -1
    value_col = -1
    measurement_col = -1
    measurement_set = set()

    while (row := next(csv_reader, None)) is not None:
        if len(row) <= 1:
            # Blank row, skip
            continue
        elif row[0]  != "":
            # This is a annotation row, skip
            continue
        elif row[1] != "":
            # Header row, so get the column for "_time", "_value", and "_measurement"
            time_col = row.index("_time")
            value_col = row.index("_value")
            measurement_col = row.index(measurement_name)
        else:
            # Data row
            measurement = row[measurement_col]
            measurement_set.add(measurement)

            if measurement not in data:
                data[measurement] = []
            data[measurement].append((row[time_col], row[value_col]))

    return data

if __name__ == "__main__":
    idx = 1

    convert_to_cst = False

    alternate_name_col = None

    while idx < len(sys.argv):
        arg = sys.argv[idx]
        idx += 1
        if arg == "-h" or arg == "--help":
            print(f"Usage: {sys.argv[0]} [--cst] < input.csv > output.mp")
            print(f"Convert Influx 'Annotated CSV' to an MP file")
            print(f"  --cst: Convert the time to CST")
            sys.exit(0)
        elif arg == "--cst":
            convert_to_cst = True
        elif arg == "--col":
            if idx >= len(sys.argv):
                print("Error: --col requires an argument")
                sys.exit(1)
            alternate_name_col = sys.argv[idx]
            idx += 1
        else:
            print(f"Unknown option: {arg}")
            sys.exit(1)


    data = parse(alternate_name_col)
    for measurement in version_sort(data.keys()):
        print(f"{measurement}")
        # Sort by time
        data[measurement].sort(key=lambda x: x[0])

        if convert_to_cst:
            cst_time_zone = zoneinfo.ZoneInfo("America/Chicago")
            utc_time_zone = zoneinfo.ZoneInfo("UTC")

            for time, value in data[measurement]:
                utc_time = datetime.datetime.fromisoformat(time).astimezone(utc_time_zone)
                cst_time = utc_time.astimezone(cst_time_zone)
                print(f"{cst_time.isoformat()}\t{value}")
        else:
            for time, value in data[measurement]:
                print(f"{time}\t{value}")
