#!/bin/sh
# Check if file exists
if [ -f v4_Minimum_Energy_Performance_Calculator-v06.xlsm ]; then
    echo "File exists"
else
    curl -L -s https://www.usgbc.org/sites/default/files/2021-07/v4_Minimum_Energy_Performance_Calculator-v06.xlsm > v4_Minimum_Energy_Performance_Calculator-v06.xlsm
fi
