#!/usr/bin/env python3
import sys

data = [line.split("\t") for line in sys.stdin.read().splitlines()]

before_baseline = 0
in_baseline = 1
between_baseline_and_proposed = 2

baseline_start_row = -1
proposed_start_row = -1

state = before_baseline

def remove_energy_type(input_str):
    # Remove everything after the first '(' and then strip whitespace
    return input_str.split("(")[0].strip()

print("rows = {")

for row_num, row in enumerate(data, 1):
    if state == in_baseline:
        if row[1].strip() != "" and row[1].strip() != "End_Use" and "Total energy consumption" not in row[1]:
            print(f"  (\"{remove_energy_type(row[1])}\", \"{row[4].strip()}\"): {row_num},")
        elif "Total energy consumption" in row[1]:
            state = between_baseline_and_proposed
            continue
    elif state == before_baseline:
        if row[1] == "End Use":
            state = in_baseline
            baseline_start_row = row_num
        else:
            continue
    elif state == between_baseline_and_proposed:
        if row[1] == "End Use":
            proposed_start_row = row_num
            break
        else:
            continue

print("}")

print(f"offset = {proposed_start_row - baseline_start_row}")
