#!/bin/sh

# This is script to be used with the `lf` file manager.

# Receives the following arguments:
# $1: The path to the file to be opened.
# $2: Width of the preview pane.
# $3: Height of the preview pane.
# $4: Horizontal position of the preview pane.
# $5: Vertical position of the preview pane.

case "$1" in
    *.xlsx|*.XLSX) excelchop "$1" ;;
    *.zip|*.ZIP) unzip -l "$1" ;;
    *.docx|.DOCX) pandoc --to plain "$1" ;;
    *) bat-lf-previewer.sh "$1" "$3" ;;
esac

