#!/bin/sh

# This is script to be used with the `lf` file manager.

# Receives the following arguments:
# $1: The path to the file to be opened.
# $2: Width of the preview pane.
# $3: Height of the preview pane.
# $4: Horizontal position of the preview pane.
# $5: Vertical position of the preview pane.

case "$1" in
    *.xlsx|*.XLSX|*.xlsm) excelchop "$1" ;;
    *.zip|*.ZIP|*.xbk) unzip -l "$1" ;;
    *.docx|.DOCX) pandoc --to plain "$1" ;;
    *.png|*.PNG|*.jpg|*.JPG) chafa "$1" ;;
    *.tar.gz|*.TAR.GZ) tar -tzf "$1" ;;
    *.tar) tar -tf "$1" ;;
    *.eml) memail parse "$1" ;;
    *) bat-lf-previewer.sh "$1" "$3" ;;
esac
