#!/bin/sh

if test "$1" = "-h" || test "$1" = "--help"; then
    cat <<EOF
newreport

Creates a new technical memo from our company library.
EOF
exit 0
fi

if test -f '/mnt/c/Users/mpaulus/Command Commissioning/Library - Resources/Templates/ccllc-technical-memo-template.docx'; then
    TEMPLATE='/mnt/c/Users/mpaulus/Command Commissioning/Library - Resources/Templates/ccllc-technical-memo-template.docx'
elif test -f '/mnt/c/Users/mpaulus/Command Commissioning/Library - Documents/Resources/Templates/ccllc-technical-memo-template.docx'; then
    TEMPLATE='/mnt/c/Users/mpaulus/Command Commissioning/Library - Documents/Resources/Templates/ccllc-technical-memo-template.docx'
else
    echo "Could not find the template file."
    exit 1
fi

if test -n "$1"; then
    file_name="$*"
    case "$file_name" in

        *.docx)
            cp "$TEMPLATE" "$file_name" ;;
        *)
            cp "$TEMPLATE" "$file_name".docx ;;
    esac
else
    printf "No file name passed.\n"
fi
