#!/bin/sh

if test "$1" = "-h" || test "$1" = "--help"; then
    cat <<EOF
newreport

Creates a new technical report from our company library.
EOF
exit 0
fi

[ -n "$1" ] && cp '/mnt/c/Users/mpaulus/Command Commissioning/Library - Resources/Templates/ccllc-technical-report-template.docx' "$1"
