#!/bin/sh

# $1 is input file, otherwise stdin
# Remove empty lines, then print 'i_XX = ' before each line
if [ -z "$1" ]; then
    sed '/^ *$/d' /dev/stdin | awk '{printf "  i_%s = %s\n", NR, $0}'
else
    sed '/^ *$/d' "$1" | awk '{printf "  i_%s = %s\n", NR, $0}'
fi
