#!/bin/sh
# If a build of Neovim from source is found, use that.
if test -f "$REPOS"/neovim/build/bin/nvim; then
    env VIMRUNTIME="$REPOS"/neovim/runtime "$REPOS"/neovim/build/bin/nvim "$@"
else
    /usr/bin/nvim "$@"
fi
# vim:ft=sh
