#!/bin/sh

if test "$1" = "-h" || test "$1" = "--help"; then
    cat <<EOF
USAGE:
ocr file

This uses tesseract under the hood.
EOF
exit 0
fi

if command -v tesseract >/dev/null 2>&1; then
    tesseract -l eng "$1" "$(printf "%s" "$1" | sed 's/\.[^.]*$//')"
else
    printf "tesseract command not found."
fi

