#!/usr/bin/env python3

import fitz  # Import the PyMuPDF library
import sys
import os
import pathlib

def merge_pdfs_with_bookmarks(pdf_paths, output_path, filename_bookmark_mode):
    merged_document = fitz.open()  # Create a new empty PDF document

    page_offset = 0  # Keep track of the number of pages to adjust bookmark page numbers
    bookmarks = []  # List to hold all bookmarks

    # Loop through all provided PDF files
    for pdf_path in pdf_paths:
        with fitz.open(pdf_path) as doc:

            if filename_bookmark_mode:
                # Retrieve the current document's filename
                filename = pathlib.Path(pdf_path).stem
                # Add the filename as a bookmark, minus the extension
                page = 1 + page_offset
                bkmk = [1, filename, page]
                print(bkmk)
                bookmarks.append(bkmk)
            else:
                # Retrieve the current document's bookmarks (if any)
                current_bookmarks = doc.get_toc(simple=False)
                # [level, title, 1-based page, {optional dict}]
                # Adjust the current document's bookmark page numbers and add to the main list
                for bkmk in current_bookmarks:
                    # Increment the page number by the current offset
                    bkmk[2] += page_offset
                    bkmk[3]["page"] += page_offset - 1
                    bookmarks.append(bkmk)

            # Update the page offset
            page_offset += doc.page_count

            # Append the document
            merged_document.insert_pdf(doc, annots=True)


    num_inserted = merged_document.set_toc(bookmarks)
    print(f"Inserted {num_inserted} bookmarks", file=sys.stderr)
    # Save the merged document
    merged_document.save(output_path)

    print("New bookmarks:")
    for bkmk in merged_document.get_toc(simple=False):
        print(bkmk)

    merged_document.close()


help_message = "Usage: pdfmerge.py [--filename] <output file> <input files...>"

if __name__ == "__main__":
    index = 1

    filename_bookmark_mode = False

    while index < len(sys.argv):
        if sys.argv[index] == "-h" or sys.argv[index] == "--help":
            print(help_message)
            sys.exit(1)
        elif sys.argv[index] == "--filename":
            filename_bookmark_mode = True
            index += 1
        else:
            break

    if len(sys.argv) - index < 2:
        print(help_message)
        sys.exit(1)

    output_file = sys.argv[index]
    input_files = sys.argv[index + 1:]

    if output_file.strip() == "":
        print("Output file cannot be empty")
        sys.exit(1)

    # Merge the PDFs
    merge_pdfs_with_bookmarks(input_files, output_file, filename_bookmark_mode)
