#!/bin/sh

# Print tab separated data of the bookmarks for a pdf.

# DEPENDENCIES:
# qpdf and jq

# OUTPUT:
# <Page, 1-based><TAB><Bookmark Title>
filename="$1"

qpdf --json-key=outlines --json "$filename" | jq -r \
'
.outlines[] |
recurse(.kids[]) |
[ .destpageposfrom1, .title] |
@tsv
'
