#!/bin/sh

if ! command -v remind >/dev/null 2>&1; then
    printf 'remind not found.\n'
    exit 1
fi

first_reminder="$(rem | awk 'NR > 2 && $0 !~ /^ *$/' | shuf -n 1 | sed 's/ *$//')"

if [ -n "$first_reminder" ]; then
    printf '%s\n' "$first_reminder"
else
    printf "No reminders.\n"
fi
