#!/bin/sh

first_reminder="$(remind ~/.config/remind/remind.rem | awk 'NR > 2 && $0 !~ /^ *$/' | shuf -n 1 | sed 's/ *$//')"

if [ -n "$first_reminder" ]; then
    printf '%s' "$first_reminder"
else
    printf "No reminders.\n"
fi
