#!/bin/sh

# Search for .gitignore in the current directory

if [ -f .gitignore ]; then
    GITIGNORE=.gitignore
else
    echo "No .gitignore file found in the current directory"
    exit 1
fi

if [ -z "$GITIGNORE" ]; then
    echo "No .gitignore file found in the current directory"
    exit 1
fi

while read -r line; do
    printf '%s\n' "$line"
    if printf '%s\n' "$line" | grep -q '^# REDOGI'; then
        redogi
        break
    fi
done < .gitignore > tmp && mv tmp .gitignore
