#!/bin/sh

if test "$1" = "-h" || test "$1" = "--help"; then
    cat <<EOF
tabcut <field specifier> <file>

This script uses normal 'cut' program to do actual work.
EOF
exit 0
fi

if test "$#" -lt 2; then
    # Use standard input
    cut -d '	' -f "$1" -
else
    # Use file
    cut -d '	' -f "$1" "$2"
fi
