#!/bin/sh

# Check for 'tabula.*jar' file in the LOCALBIN
TABULA_JARS="$(find "$LOCALBIN" -name 'tabula*.jar' -type f)"

if [ -n "$TABULA_JARS" ]; then
    # Use the latest version if multiple
    TABULA_JAR="$(echo "$TABULA_JARS" | sort -V | tail -n 1)"
else
    printf "ERROR: tabula.jar not found in %s\n" "$LOCALBIN"  >&2
    exit 1
fi

# Run tabula.jar
java -jar "$TABULA_JAR" "$@"
