#!/bin/sh

curl --silent "https://api.todoist.com/rest/v2/tasks" \
    -X POST \
    --data '{"content": "'"$1"'", "project_id": 2315202256 }' \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer $TODOIST_TOKEN"
