#!/bin/sh
curl 'http://certificants.ashrae.org/Search' \
 -X POST \
 -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:94.0) Gecko/20100101 Firefox/94.0' \
 -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8' \
 -H 'Accept-Language: en-US,en;q=0.5' --compressed \
 -H 'Referer: http://certificants.ashrae.org/Search' \
 -H 'Content-Type: application/x-www-form-urlencoded' \
 -H 'Origin: http://certificants.ashrae.org' \
 -H 'DNT: 1' \
 -H 'Connection: keep-alive' \
 -H 'Cookie: ASP.NET_SessionId=s4b34qxa22oiskkk2rr2bknf' \
 -H 'Upgrade-Insecure-Requests: 1' \
 -H 'Sec-GPC: 1' \
 -H 'Pragma: no-cache' \
 -H 'Cache-Control: no-cache' \
 --data-raw \
 'fname=&lname=&org=&licTypes=BEMP&city=&state=TX&zip=&countries=&data_length=25'
