#!/usr/bin/env python3

import sys

lowercase_words = {
    'a', 'an', 'the', 'and', 'but', 'or', 'for', 'nor', 'on', 'at', 'to', 'from', 'by', 'over', 'per'
}

word_map = {
    'co2': 'CO₂',
    'vfd': 'VFD',
    'hoa': 'HOA',
}

def title_word(word: str):
    split_on_slash: list[str] = word.split('/')

    if len(split_on_slash) > 1:
        return '/'.join(title_word(part) for part in split_on_slash)
    else:
        lower_case_word = word.lower()
        if lower_case_word in word_map:
            return word_map[lower_case_word]

        if lower_case_word in lowercase_words:
            return lower_case_word

        return word.capitalize()



def to_title_case(s):
    words = s.split()
    title_case_words = [title_word(word) for word in words]
    return ' '.join(title_case_words)

def run():
    for line in sys.stdin:
        print(to_title_case(line.strip()))

if __name__ == '__main__':
    run()
