#!/usr/bin/env python3

import sys
lines = sys.stdin.read().splitlines()

def to_var_name(input_str: str) -> str:
    # Make all lowercase, replace spaces with underscores
    return input_str.lower().replace(" ", "_")

if len(sys.argv) > 1:
    prefix_name_var = to_var_name(sys.argv[1]) + "_"
    prefix_name = sys.argv[1] + " "

else:
    prefix_name_var = ""
    prefix_name = ""


if len(lines) == 1:
    print(f"node_{prefix_name_var}{to_var_name(lines[0])}_inlet = name + ' {prefix_name}{lines[0]} Inlet Node'")
    print(f"node_{prefix_name_var}{to_var_name(lines[0])}_outlet = name + ' {prefix_name}{lines[0]} Outlet Node'")


else:
    print(f"node_{prefix_name_var}{to_var_name(lines[0])}_inlet = name + ' {prefix_name}{lines[0]} Inlet Node'")
    print(f"node_{prefix_name_var}{to_var_name(lines[0])}_outlet = name + ' {prefix_name}{lines[0]} Outlet Node'")

    for idx, line in enumerate(lines[1:], 1):
        print(f"node_{prefix_name_var}{to_var_name(line)}_inlet = name + ' {prefix_name}{lines[idx - 1]} Outlet Node'")
        print(f"node_{prefix_name_var}{to_var_name(line)}_outlet = name + ' {prefix_name}{line} Outlet Node'")
