#!/usr/bin/env python3
import sys

def main():
    if len(sys.argv) != 2:
        print("Usage: {} < FILE".format(sys.argv[0]))
        sys.exit(1)

    data = [line.split("\t") for line in sys.stdin.read().splitlines()]

    header_trends = data[0][1:]

    for header in header_trends:
        print(header, end='\n')

    header_idx = 1

    while header_idx < len(data[0]):
        for row_idx in range(1, len(data)):
            value = data[row_idx][header_idx]
            if value.strip() == '':
                continue
            print(f"{data[row_idx][0]}\t{value}", end='\n')
        header_idx += 1

if __name__ == '__main__':
    main()
