#!/bin/sh

# Print out the headers in a TSV file
# The -q removes the added filename text, the -n 1 for just the first line.
# This works properly even if multiple files are passed as arguments like:
# csvhead file1 file2
# Removes column headers that look like time stamps.

# Check if $1 is '-n', then no sort

if [ "$1" = "-n" ]; then
    shift
    head -q -n 1 "$@" | tr '\t' '\n' | tr -d '\r' | awk '
    BEGIN {
    ts["timestamp"]
    ts["datetime"]
    ts["time stamp"]
    ts["date"]
    ts["time"]
}

!(tolower($0) in ts)
'

else

head -q -n 1 "$@" | tr '\t' '\n' | tr -d '\r' | awk '
    BEGIN {
    ts["timestamp"]
    ts["datetime"]
    ts["time stamp"]
    ts["date"]
    ts["time"]
}

!(tolower($0) in ts)
' | sort -V

fi
