#!/bin/sh
set -e

# tt stands for 'Toggl track'
PROJ="$(toggl projects | sort -V | fzf)"

if [ -z "$PROJ" ]; then
    exit 1
fi

# Prompt for a description
printf "Description: "
read -r DESC

if [ -z "$DESC" ]; then
    exit 1
fi

toggl start "$PROJ" "$DESC"
