#!/bin/sh

# The purpose of this script is to unzip file to a folder
# with the same name. The folder will be in the same directory
# as the passed in file.

helptext() {
    cat <<EOF
unzip file.zip

The purpose of this script is to unzip file to a folder
with the same name. The folder will be in the same directory
as the passed in file.
EOF
}

if test "$1" = "-h" || test "$1" = "--help"; then
    helptext
exit 0
fi

if test "$#" -ne 1; then
    printf "unzipd expects a single argument, the zip file.\n\n"
    helptext
    exit 1
fi

filename="$(basename "$1")"
unzip "$1" -d "$(dirname "$1")"/"${filename%.*}"
