#!/bin/sh

# Taken from https://unix.stackexchange.com/a/60698/296724
string="$*"; format=; set --
while
literal=${string%%[!-._~0-9A-Za-z]*}
case "$literal" in
  ?*)
    format=$format%s
    set -- "$@" "$literal"
    string=${string#$literal};;
esac
case "$string" in
  "") false;;
esac
do
tail=${string#?}
head=${string%$tail}
format=$format%%%02x
set -- "$@" "'$head"
string=$tail
done
# The variable expansion is to create the printf format, so
# having the varialbe in the format is desired.
# shellcheck disable=SC2059
printf "$format\\n" "$@"
