#!/bin/sh
# Print out USERPROFILE Windows environment variable
set -e
# Need to change into a windows dir before cmd.exe or else it complains.
cd /mnt/c/ || exit 1
wslpath "$(cmd.exe /C 'echo %USERPROFILE%' | tr -d '\r')"
