#!/bin/sh


if test "$1" = "-h" || test "$1" = "--help"; then
    cat <<EOF
Usage: wordkill [file]
EOF
exit 0
fi

if [ -z "$1" ]; then
    echo "Usage: wordkill [file]"
    exit 1
fi

pid="$(tasklist.exe '/FI' 'IMAGENAME eq WINWORD.EXE' '/FO:LIST' '/V' | awk -v searchfile="$1" '
BEGIN { FS=OFS=":" }

$1 ~ /PID/ {

    gsub(/[ \r]/, "", $2)

    current_pid = $2

}

$1 ~ /Window Title/ && $2 ~ searchfile {
    print current_pid
    exit 0
}')"

if [ -n "$pid" ]; then
    taskkill.exe '/PID' "$pid"
fi
